### ISSUE TITLE
Bug in script for Stage 1 validation

### ISSUE THREAD

**Issue by PriyavKaneria** [PriyavKaneria/Anonymously-New#1]
When giving greek alphabet input, it still shows a Correct answer popup after showing close enough

**Comment by sanskaromar** [comment]
@PriyavKaneria Can you show light on how to reproduce the bug at my end?

**Comment by PriyavKaneria** [comment]
On the page https://priyavkaneria.github.io/Anonymously-New/access_key.html
If the user gets the hint and enters `γνώση` in the input, it should give close enough popup but not the success popup
