### ISSUE TITLE
Critical bug in Level 1: User bypass with wrong key

### ISSUE THREAD

**Issue by sanskaromar** [PriyavKaneria/Anonymously-New#8]
**Describe the bug**
In stage 1, sometimes users are able to bypass the stage even after entering wrong key, that too without "Stage cleared" popup.

**To Reproduce**
1. Go to https://priyavkaneria.github.io/Anonymously-New/access_key.html
2. Click on the only Input field in page
3. Enter any random key for example 1, 23, meow etc
4. You will be redirected to next stage without stage successful popup
5. Note that we entered wrong keys still we were able to pass

**Comment by PriyavKaneria** [comment]
@sanskaromar You can work on this issue if you want
